#spring:
#  application:
#    name: massif-main
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848    # Nacos server??
#      config:
#        server-addr: localhost:8848    # Nacos server??
#        file-extension: yaml          # ??????
#        namespace: 0efa7ad3a5427e28baa99ba6ef65814a
#        group: DEFAULT_GROUP

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/massif?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456

server:
  port: 8081

logging:
  level:
    com.baomidou.mybatisplus.mapper: debug

